### ISSUE TITLE
Seldom error in stageDeployToOpenshift (ArrayIndexOutOfBounds)- when checking for new deployment

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#142]
**Describe the bug**
.....
java.lang.ArrayIndexOutOfBoundsException: 6
	at org.codehaus.groovy.runtime.dgmimpl.arrays.ObjectArrayGetAtMetaMethod.invoke(ObjectArrayGetAtMetaMethod.java:41)
....
	at stageDeployToOpenshift.call(/var/lib/jenkins/jobs/trainods-cd/jobs/trainods-cd-be-golang-master/builds/2/libs/ods-library/vars/stageDeployToOpenshift.groovy:23)
	at ___cps.transform___(Native Method)

**To Reproduce**
hard, only if deployment scheduling takes forever 

**Expected behavior**
no error, deployment search continues

**Affected version (please complete the following information):**
 - OpenDevStack [1.2.x/master]

**Comment by michaelsauter** [comment]
I will address this when I redo that logic using other `oc` commands. I will also add timeouts to all calls.

**Comment by michaelsauter** [comment]
This should be fixed with #147.
