### ISSUE TITLE
Image author / commit empty in oc image built thru jenkins shared lib

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#47]
For some reason, the author of the image produced by the Jenkins build is unknown. This information should be set though as the commit author is known.

**Comment by clemensutschig** [comment]
the difference is driven by the BC - if the BC is based on a GIT commit / git source then the author of the commit is taken

if the source is binary ...

Author
Unknown
Built
3 months ago
Digest
sha256:80bffd16ff2694e8b247206d0ec623f6def14306ec878ebe7f89714d48ca9041
Identifier
sha256:7d507dd355c894c43eeca9f943bd53c7bebbf61018ef5fada1cbb4ca7c77ab46
Labels
io.openshift.build.name=be-spring-boot-1-1
io.openshift.build.namespace=cle335-test

- we have to fix this asap - because it kills tracibility!

**Comment by clemensutschig** [comment]
see https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsContext.groovy#L116 

we have the commit / branch etc ... we may need the author and the message as well - but then 

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/vars/stageStartOpenshiftBuild.groovy#L10

could use this :)

**Comment by clemensutschig** [comment]
**update:**
the author on the image - comes from dockerfile's author .. BUT 

the *io. pieces come from the build config instance
`
spec:
  revision:
    git:
      author:
        email: xxx
        name: clemensutschig
      commit: 1f0add480c5b08125f95c917a9ed2ba3c2bcdf2d
      committer:
        email: xxxx
        name: clemensutschig
      message: Merge branch 'feature/add_cnes_sq_jar' into production_BI_DEV
`

**Comment by michaelsauter** [comment]
@renedupont Can you look into this - let me know if you need help.

**Comment by renedupont** [comment]
I talked to @michaelsauter about it and started working on it, should be done in a couple of days.

**Comment by renedupont** [comment]
After implementing this for the label `io.openshift.build.commit.author` it turns out, that this is not the label that openshift pulls for the Author field in the Details view of the Image.
It just showed it like this there:
![image](https://user-images.githubusercontent.com/39172761/52863452-30502880-3138-11e9-870b-4e3bf70ea44c.png)

What I found out though is that this Author field is the MAINTAINER of the Docker image.
I put this in the dockerfile 
![image](https://user-images.githubusercontent.com/39172761/52863811-0fd49e00-3139-11e9-9108-129afee46043.png)
and it was filled then in openshift:
![image](https://user-images.githubusercontent.com/39172761/52863849-267af500-3139-11e9-8a28-9bfa66c78858.png)


This seems to be rather unhelpful regarding tracibility.

The question is now what we want to have here?

**Comment by clemensutschig** [comment]
Pur all the Info into label 
. Commit hash message Author and branch..  and date.. ;-)

**Comment by clemensutschig** [comment]
so here is the list of thngs we should put in
- source repo URL
- branch
- commit hash
- message
- author
- time of commit
- jenkins build job url
- date of build
- ODS shared lib version

**Comment by renedupont** [comment]
@clemensutschig I was now able to retrieve all of the information and present them as labels, BUT the shared lib version that we wanted to get via

`config.odsSharedLibVersion = script.env["library.ods-library.version"]`

causes a RejectAccessException during the build since it runs in a groovy sandbox. The precise exception is:

`org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object java.lang.String
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectStaticMethod(StaticWhitelist.java:189)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetArray(SandboxInterceptor.java:447)
	at org.kohsuke.groovy.sandbox.impl.Checker$10.call(Checker.java:415)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetArray(Checker.java:420)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getArray(SandboxInvoker.java:45)
	at com.cloudbees.groovy.cps.impl.ArrayAccessBlock.rawGet(ArrayAccessBlock.java:21)
	at org.ods.OdsContext.assemble(file:/var/lib/jenkins/jobs/owasp-cd/jobs/owasp-cd-be-spring-boot-2-master/builds/37/libs/ods-library/src/org/ods/OdsContext.groovy:44)
	at org.ods.OdsPipeline.execute(file:/var/lib/jenkins/jobs/owasp-cd/jobs/owasp-cd-be-spring-boot-2-master/builds/37/libs/ods-library/src/org/ods/OdsPipeline.groovy:28)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor410.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:331)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

To allow that access it is possible to manually allow it in Jenkins Web UI under Script Approval:
![image](https://user-images.githubusercontent.com/39172761/53681890-0da14080-3cf0-11e9-9f9c-5009f3110a60.png)
After allowing, it shows successfully the lib version, in my case it is the branch name I am testing it on.

Since we obviously don't want to do this manually for every jenkins instance, besides being a security risk according to the script approval message, the question is how we deal with this. I remember there were similar issues in the past with this sandbox rejecting access, any idea how it was dealt with @michaelsauter ?

**Comment by clemensutschig** [comment]
@renedupont ' then lets leave this one out.

**Comment by clemensutschig** [comment]
Other Option- sh "env | grep"

**Comment by renedupont** [comment]
`echo script.sh(script: 'env|grep', returnStdout: true)`
This resulted in 
`ERROR: script returned exit code 2`
Then I did
`echo script.sh(script: 'env|sort', returnStdout: true)`
to see all env vars but regarding the ods library version it just showed as expected:
`library.ods-library.version=feature/branchname`

I'll take it out for now since it seems not to be accessible without this security issue.

**Comment by clemensutschig** [comment]
env | grep "library.ods-library.version" should do .. grep expects an argument WHAT do search for ... :)

<pre>
$ env | grep HOST
HOSTNAME=....
</pre>

**Comment by renedupont** [comment]
oh thank you, that helped 👍 
It ended up being this:
`script.sh(script: "env | grep 'library.ods-library.version' | cut -d= -f2", returnStdout: true)`

**Comment by clemensutschig** [comment]
Nice. Pull in michaelsauter tmrw to help with Upstream

**Comment by michaelsauter** [comment]
@clemensutschig @renedupont I realised what you used for `ODS openshift build server (openshift.server)` returns a private IP address :( I guess we can leave that out ...
