### ISSUE TITLE
java.lang.RuntimeException: Error: unable to unstash JUnit XML reports, type 'unit' for

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-jenkins-shared-library#498]
`JenkinsService.stashTestResults(...)` resolves the stash path name to a different name than the `Stage.getTestResults(...)` class. This leads to the exception:
``` 
java.lang.RuntimeException: Error: unable to unstash JUnit XML reports, type 'unit' for repo 'edpgo-app-backend' from stash 'test-reports-junit-xml-edpgo-app-backend-8'.
```

This problem is caused because there are two to different places in code that construct the junit stash name path in a different way. 
In the logs attached below see that the junit stash path name is resolved to 2 different names:
```
test-reports-junit-xml-app-backend-8
```

```
test-reports-junit-xml-edpgo-app-backend-8
```

Proposed Solution:
Move the junit stash path name implementation to a util method and call it from the  JenkinsService.stashTestResults(...)` and `Stage.getTestResults(...)`.
Because `Stage` class uses JenkinsService to avoid creating a circular dependency the best place to add this method is the class `JenkinsService`.

Environment:
This is impacting branch 3.x. Not sure if same bug exists in master branch.

Logs:
``` 
To Reproduce provision a repo with spring boot component and a release manager component. 
Run the pipeline 

[Pipeline] echo
Attempting to stash testresults from location: 'build/test-results/test'
[Pipeline] sh
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label
+ mkdir -p build/test-results/test build/test-results/test
+ cp -rf build/test-results/test/TEST-org.opendevstack.edpgo.app_backend.AppBackendApplicationTests.xml build/test-results/test/binary build/test-results/test
+ true
cp: 'build/test-results/test/TEST-org.opendevstack.edpgo.app_backend.AppBackendApplicationTests.xml' and 'build/test-results/test/TEST-org.opendevstack.edpgo.app_backend.AppBackendApplicationTests.xml' are the same file
cp: 'build/test-results/test/binary' and 'build/test-results/test/binary' are the same file
[Pipeline] sh
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label
+ ls -la build/test-results/test/TEST-org.opendevstack.edpgo.app_backend.AppBackendApplicationTests.xml
+ wc -l
[Pipeline] echo
DEBUG: Found 1 test files in 'build/test-results/test'
[Pipeline] junit
Recording test results
[Pipeline] stash
Stashed 1 file(s)
[Pipeline] echo
DEBUG: [app-backend] ODS Component Pipeline 'app-backend-8'
ODS Build Artifacts 'app-backend': 
{
    "builds": {
        "app-backend": {
            "buildId": "app-backend-8",
            "image": "172.30.1.1:5000/edpgo-dev/app-backend@sha256:15c7201551203ab169bbcfe3115374b43d1dc1978b28285366a92f181acc35c3"
        }
    },
    "deployments": {
        "app-backend": {
            "podName": "app-backend-8-nshg2",
            "podNamespace": "edpgo-dev",
            "podMetaDataCreationTimestamp": "2020-11-23T10:32:33Z",
            "deploymentId": "app-backend-8",
            "podNode": "localhost",
            "podIp": "172.17.0.41",
            "podStatus": "Running",
            "podStartupTimeStamp": "2020-11-23T10:32:33Z",
            "containers": {
                "app-backend": "172.30.1.1:5000/edpgo-dev/app-backend@sha256:15c7201551203ab169bbcfe3115374b43d1dc1978b28285366a92f181acc35c3"
            }
        }
    },
    "sonarqubeScanStashPath": "scrr-report-app-backend-8",
    "SCRR": "SCRR-edpgo-app-backend.docx",
    "SCRR-MD": "SCRR-edpgo-app-backend.md",
    "testResultsFolder": "build/test-results/test",
    "testResults": "1",
    "xunitTestResultsStashPath": "test-reports-junit-xml-app-backend-8"
} (took 257401 ms)
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] }
[Pipeline] // load
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] echo
DEBUG: Collected ODS build artifacts for repo 'edpgo-app-backend': [builds:[app-backend:[buildId:app-backend-8, image:172.30.1.1:5000/edpgo-dev/app-backend@sha256:15c7201551203ab169bbcfe3115374b43d1dc1978b28285366a92f181acc35c3]], deployments:[app-backend:[podName:app-backend-8-nshg2, podNamespace:edpgo-dev, podMetaDataCreationTimestamp:2020-11-23T10:32:33Z, deploymentId:app-backend-8, podNode:localhost, podIp:172.17.0.41, podStatus:Running, podStartupTimeStamp:2020-11-23T10:32:33Z, containers:[app-backend:172.30.1.1:5000/edpgo-dev/app-backend@sha256:15c7201551203ab169bbcfe3115374b43d1dc1978b28285366a92f181acc35c3]]], sonarqubeScanStashPath:scrr-report-app-backend-8, SCRR:SCRR-edpgo-app-backend.docx, SCRR-MD:SCRR-edpgo-app-backend.md, testResultsFolder:build/test-results/test, testResults:1, xunitTestResultsStashPath:test-reports-junit-xml-app-backend-8, CREATED_BY_BUILD:WIP/8]
[Pipeline] }
[Pipeline] // dir
[Pipeline] echo
DEBUG: Collecting JUnit XML Reports ('unit') for edpgo-app-backend
[Pipeline] dir
Running in /var/lib/jenkins/jobs/edpgo-cd/jobs/edpgo-cd-app-release-manager-master/workspace/xunit/edpgo-app-backend/unit
[Pipeline] {
[Pipeline] unstash
[Pipeline] echo
2020-11-23 10:32:42Z Could not find any files of type 'JUnit XML Report' to unstash for name 'test-reports-junit-xml-edpgo-app-backend-8'
[Pipeline] }
[Pipeline] // dir
[Pipeline] echo
WARN: Error: unable to unstash JUnit XML reports, type 'unit' for repo 'edpgo-app-backend' from stash 'test-reports-junit-xml-edpgo-app-backend-8'.
[Pipeline] }
Failed in branch edpgo-app-backend
[Pipeline] // parallel
[Pipeline] }
Failed in branch Build
[Pipeline] // parallel
[Pipeline] echo
WARN: Error occured within the orchestration pipeline: Error: unable to unstash JUnit XML reports, type 'unit' for repo 'edpgo-app-backend' from stash 'test-reports-junit-xml-edpgo-app-backend-8'.
[Pipeline] echo
DEBUG: [jira-update-release-EDPGO-38]  (took 122 ms)
[Pipeline] echo
[Build] **** ENDED orchestration stage **** (took 260274 ms)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] echo
[ods-mro-pipeline] **** ENDED orchestration pipeline **** (took 300185 ms)
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.RuntimeException: Error: unable to unstash JUnit XML reports, type 'unit' for repo 'edpgo-app-backend' from stash 'test-reports-junit-xml-edpgo-app-backend-8'.
	at org.ods.orchestration.Stage.getTestResults(Stage.groovy:110)
	at org.ods.orchestration.BuildStage.run(BuildStage.groovy:44)
	at org.ods.orchestration.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:365)
	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:153)
	at org.ods.orchestration.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:309)
	at ___cps.transform___(Native Method)
```

**Comment by stitakis** [comment]
@metmajer @renedupont @michaelsauter I have a fix that I'm testing at this moment... is this bug familiar to you? Or my release manager is not properly configured?

**Comment by stitakis** [comment]
@metmajer @renedupont @michaelsauter I found out that the my release manager configuration was wrong. I fix it by replacing in `repositories` section the component id from `edpgo-app-backend` to `app-backend`. This solved the problem. I'll close this item now.
