### ISSUE TITLE
latest master broken on wrong method parameters and deploymentinfo.getPod

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#526]
from: https://4e53c33a6387.ngrok.io/images/current_log_master.tar.gz

-> rm quickstarts fail -> wrong method params
```
�[0;32m    amazon-ebs: hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.ods.services.OpenShiftService.getResourcesForComponent() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl, java.lang.String, java.lang.String) values: [unitt-dev, DeploymentConfig, app=unitt-golang]�[0m
�[0;32m    amazon-ebs: Possible solutions: getResourcesForComponent(java.lang.String, java.util.List, java.lang.String)�[0m
�[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)�[0m
�[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)�[0m
�[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)�[0m
�[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)�[0m
�[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)�[0m
�[0;32m    amazon-ebs: 	at org.ods.orchestration.phases.FinalizeOdsComponent.verifyDeploymentsBuiltByODS(FinalizeOdsComponent.groovy:125)�[0m
�[0;32m    amazon-ebs: 	at org.ods.orchestration.phases.FinalizeOdsComponent.run(FinalizeOdsComponent.groovy:38)�[0m
�[0;32m    amazon-ebs: 	at org.ods.orchestration.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:323)�[0m
�[0;32m    amazon-ebs: 	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:153)�[0m
�[0;32m    amazon-ebs: 	at org.ods.orchestration.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:309)�[0m
```

and mono-repo qs fail:
```
�[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label�[0m
�[0;32m    amazon-ebs: + oc -n unitt-dev rollout status DeploymentConfig/monorepo-iq-test --watch=true�[0m
�[0;32m    amazon-ebs: Waiting for rollout to finish: 0 out of 1 new replicas have been updated...�[0m
�[0;32m    amazon-ebs: Waiting for rollout to finish: 0 out of 1 new replicas have been updated...�[0m
�[0;32m    amazon-ebs: Waiting for rollout to finish: 0 of 1 updated replicas are available...�[0m
�[0;32m    amazon-ebs: Waiting for latest deployment config spec to be observed by the controller loop...�[0m
�[0;32m    amazon-ebs: replication controller "monorepo-iq-test-1" successfully rolled out�[0m
�[0;32m    amazon-ebs: [Pipeline] }�[0m
�[0;32m    amazon-ebs: [Pipeline] // timeout�[0m
�[0;32m    amazon-ebs: [Pipeline] sh�[0m
�[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label�[0m
�[0;32m    amazon-ebs: + oc -n unitt-dev get DeploymentConfig/monorepo-iq-test -o 'jsonpath={.status.latestVersion}'�[0m
�[0;32m    amazon-ebs: [Pipeline] sh�[0m
�[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label�[0m
�[0;32m    amazon-ebs: + oc -n unitt-dev get rc/monorepo-iq-test-1 -o 'jsonpath={.metadata.annotations.openshift\.io/deployment\.phase}'�[0m
�[0;32m    amazon-ebs: [Pipeline] echo�[0m
�[0;32m    amazon-ebs: Rollout #1 of DeploymentConfig 'monorepo-iq-test' successful.�[0m
�[0;32m    amazon-ebs: [Pipeline] sh�[0m
�[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label�[0m
�[0;32m    amazon-ebs: + oc -n unitt-dev get pod -l deployment=monorepo-iq-test-1 -o json�[0m
�[0;32m    amazon-ebs: [Pipeline] }�[0m
�[0;32m    amazon-ebs: [Pipeline] // stage�[0m
�[0;32m    amazon-ebs: [Pipeline] echo�[0m
�[0;32m    amazon-ebs: [Deploy to OpenShift-monorepo-iq-test] **** ENDED stage 'Deploy to OpenShift' for component 'monorepo-iq-test' branch 'master' **** (took 10395 ms)�[0m
�[0;32m    amazon-ebs: [Pipeline] stage�[0m
�[0;32m    amazon-ebs: [Pipeline] { (Test Deployed Component)�[0m
�[0;32m    amazon-ebs: [Pipeline] sh�[0m
�[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label�[0m
�[0;32m    amazon-ebs: + oc port-forward null 8081 -n unitt-dev�[0m
�[0;32m    amazon-ebs: Error from server (NotFound): pods "null" not found�[0m
�[0;32m    amazon-ebs: [Pipeline] sh�[0m
�[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label�[0m
�[0;32m    amazon-ebs: + timeout 10s bash -c 'until ! curl -v --silent http://localhost:8081 2>&1 | grep -m 1 "Connection refused"; do sleep 1 ; done'�[0m
```
@michaelsauter  - is this because of your refactoring to use deployments now as labels,.. clearly the same thing works in 3.x

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy#L101 breaking Change?

**Comment by michaelsauter** [comment]
The second issue is because the `Jenkinsfile` uses the result of the rollout, which is a ist now. I did not know this result is used outside of tests. I'll check the other quickstarters as well now, but I think nothing else uses it.
