### ISSUE TITLE
regression? No signature of method: org.ods.orchestration.util.Project.hasFailingTests() is applicable for argument types: ()  - on master

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#675]
**Affected version (please complete the following information):**
 - OpenShift: [3.11, master]
 - OpenDevStack [master]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
[0;32m    amazon-ebs: [Pipeline] End of Pipeline[0m
[0;32m    amazon-ebs: hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.ods.orchestration.util.Project.hasFailingTests() is applicable for argument types: () values: [][0m
[0;32m    amazon-ebs: Possible solutions: getHasFailingTests(), setHasFailingTests(boolean)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.FinalizeStage.run(FinalizeStage.groovy:99)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.Stage.execute(Stage.groovy:40)[0m
```

**Comment by clemensutschig** [comment]
@metmajer @s2oBCN - I am confused about what's going on with `@NonCPS` 

any idea? I try with a fix - but this is really odd
