### ISSUE TITLE
RM: missing property exception: hasFailingTests in project ´- master

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#678]
**Describe the bug**
after refactoring, and with #675 I removed the `get` from `getHasFailingTests` - and now its breaking early . and I am very confused - I caused this, clearly ... 

**To Reproduce**
see latest master build logs on ods-core/readme

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [master]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
[0;32m    amazon-ebs: groovy.lang.MissingPropertyException: No such property: hasFailingTests for class: org.ods.orchestration.util.Project[0m
[0;32m    amazon-ebs: Possible solutions: hasFailingTests[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.BuildStage.run(BuildStage.groovy:90)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.Stage.execute(Stage.groovy:40)[0m
[0;32m    amazon-ebs: 	at ___cps.transform___(Native Method)[0m
```
@metmajer @s2oBCN

**Comment by clemensutschig** [comment]
is for the CPS annotion both needed? `get` and just `has ... `
reference: https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/util/Project.groovy#L956
