### ISSUE TITLE
Second run of Jira backed RM fails when triggered from jenkins directly 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#840]
** How to reproduce **
1. EDP project 1.2 - all data in jira
2. Start a wip run that fails because of tests
3. Search for the build config / jenkins - build with parameters - use the same parameters to trigger a new build
4. Notice failure: `Error: unable to create CSD. Could not obtain document chapter data from Jira.` 

```
java.lang.RuntimeException: Error: unable to create CSD. Could not obtain document chapter data from Jira.
	at org.ods.orchestration.usecase.LeVADocumentUseCase.getDocumentSections(LeVADocumentUseCase.groovy:1700)
	at org.ods.orchestration.usecase.LeVADocumentUseCase.createCSD(LeVADocumentUseCase.groovy:162)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:394)
	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:154)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:390)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:378)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy)
	at org.ods.orchestration.InitStage.run(InitStage.groovy:419)
	at org.ods.orchestration.Stage.execute(Stage.groovy:40)
```
I cannot explain what's happening here .. really strange .. triggering a new WIP run from Jira works totally fine ..

@metmajer

**Comment by clemensutschig** [comment]
Ha, for some reason wrong data was picked as params .. never mind - sorry ...
