### ISSUE TITLE
JiraService.createIssueType(JiraService.groovy:194) fails when description is missing - from upstream empty error.text in XUnit

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#849]
The error comes as downstream result from Tosca sending errors instead of failures …
```
	| 
, systemErr:, timestamp:2/20/2022 10:14:19 PM], [classname:Acceptance, name:VEEVACRM486_Medical Information Inquiry is completely and correctly transferred from IRep to MIS, time:362, error:[message:TestCase Failed with Failure, type:ExecutionResultState.Failed, text:], skipped:false, systemOut:	| ********************************************************************************************************
	| *** VEEVACRM486_Medical Information Inquiry is completely and correctly transferred from IRep to MIS ***
	| ********************************************************************************************************
	| ResultState: Failed
```
The problem is the “text:” that is empty – which makes downstream (JiraService) fail, especially:
```
        if (!description?.trim()) {
            throw new IllegalArgumentException('Error: unable to create Jira issue. \'description\' is undefined.')
        }
```

-------------------------------
[Pipeline] End of Pipeline
java.lang.IllegalArgumentException: Error: unable to create Jira issue. 'description' is undefined.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.ods.orchestration.service.JiraService.createIssueType(JiraService.groovy:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.ods.orchestration.service.JiraService.createIssueTypeBug(JiraService.groovy:240)
	at org.ods.orchestration.usecase.JiraUseCase.createBugsForFailedTestIssues(JiraUseCase.groovy:122)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2068)
	at org.ods.orchestration.usecase.JiraUseCase.createBugsForFailedTestIssues(JiraUseCase.groovy:119)
	at org.ods.orchestration.usecase.JiraUseCase.reportTestResultsForComponent(JiraUseCase.groovy:335)
	at org.ods.orchestration.usecase.JiraUseCase.reportTestResultsForProject(JiraUseCase.groovy:346)
	at org.ods.orchestration.TestStage.run(TestStage.groovy:72)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.callClosureForMapEntry(CpsDefaultGroovyMethods:5228)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2107)
	at org.ods.orchestration.TestStage.run(TestStage.groovy:70)
	at org.ods.orchestration.Stage.execute(Stage.groovy:40)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor388.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/service/JiraService.groovy#L193-L195

the corresponding unit test - needs to be changed as well

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/test/groovy/org/ods/orchestration/service/JiraServiceSpec.groovy#L751-L772

**Comment by clemensutschig** [comment]
please fwd port to master

**Comment by metmajer** [comment]
@jafarre-viewnext can you please assist with the forward to the master branch?

**Comment by metmajer** [comment]
@jafarre-viewnext please close this if merged to master
