### ISSUE TITLE
NonCPS function calls logger which causes CPS mismatch

### ISSUE THREAD

**Issue by albertpuente** [opendevstack/ods-jenkins-shared-library#851]
**Describe the bug**
checkIfAllIssuesHaveVersions in DocumentHistory.groovy calls logger.warn, which is a function not annotated with NonCPS, causing the function to return a string instead of a map.

**To Reproduce**
1. Run any release manager pipeline that contains issues where the version is not specified.

**Expected behavior**
The warning should not compromise the execution flow of the function.

**Affected version (please complete the following information):**
 - OpenDevStack 4.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
[](https://...)DEBUG: Retrieved latest CFTR version 1 from saved history
[Pipeline] echo
DEBUG: Parsing jira data to document history
expected to call org.ods.orchestration.util.DocumentHistory.computeEntryData but wound up catching org.ods.util.Logger.warn; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/[](...)
[Pipeline] echo
WARN: Document history not valid. We don't have a version for  the following elements'TESTBUG-252'. If you are not using versioning and its automated document history you can ignore this warning. Otherwise, make sure all the issues have a version attached to it.
[Pipeline] echo
DEBUG: parseJiraDataToDocumentHistoryEntry: versionMap = WARN: Document history not valid. We don't have a version for  the following elements'TESTBUG-252'. If you are not using versioning and its automated document history you can ignore this warning. Otherwise, make sure all the issues have a version attached to it.
[Pipeline] echo
WARN: Error: Creating document of type 'CFTR' for project 'testbug' in phase 'Test' and stage 'PRE_END' has failed: Could not find matching constructor for: org.ods.orchestration.util.DocumentHistoryEntry(java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String).
[Pipeline] echo
WARN: Error occured within the orchestration pipeline: Error: Creating document of type 'CFTR' for project 'testbug' in phase 'Test' and stage 'PRE_END' has failed: Could not find matching constructor for: org.ods.orchestration.util.DocumentHistoryEntry(java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String).
[Pipeline] echo
DEBUG: [jira-update-release-TESTBUG-210]  (took 1222 ms)
[Pipeline] echo
[Test] **** ENDED orchestration stage **** (took 292671 ms)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] echo
[ods-mro-pipeline] **** ENDED orchestration pipeline **** (took 408714 ms)
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.ods.orchestration.util.DocumentHistoryEntry(java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1732)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1532)
	at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:49)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at org.ods.orchestration.util.DocumentHistory.parseJiraDataToDocumentHistoryEntry(DocumentHistory.groovy:329)
	at org.ods.orchestration.util.DocumentHistory.load(DocumentHistory.groovy:72)
	at org.ods.orchestration.usecase.LeVADocumentUseCase.getAndStoreDocumentHistory(LeVADocumentUseCase.groovy:1643)
	at org.ods.orchestration.usecase.LeVADocumentUseCase.createCFTR(LeVADocumentUseCase.groovy:518)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:394)
	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:154)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:390)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:378)
	at org.ods.orchestration.TestStage.run(TestStage.groovy:80)
	at org.ods.orchestration.Stage.execute(Stage.groovy:40)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor332.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
Caused: java.lang.IllegalStateException: Error: Creating document of type 'CFTR' for project 'testbug' in phase 'Test' and stage 'PRE_END' has failed: Could not find matching constructor for: org.ods.orchestration.util.DocumentHistoryEntry(java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String).
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:396)
	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:154)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:390)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:378)
	at org.ods.orchestration.TestStage.run(TestStage.groovy:80)
	at org.ods.orchestration.Stage.execute(Stage.groovy:40)
	at ___cps.transform___(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor332.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

**Comment by albertpuente** [comment]
master branch does not require porting this fix since it does not call the logger
https://github.com/opendevstack/ods-jenkins-shared-library/blob/629fd7c1d97d168aa87ddb22a87be7e24e46bd22/src/org/ods/orchestration/util/DocumentHistory.groovy#L272-L277

**Comment by metmajer** [comment]
@jafarre-viewnext
